language: python
python: '2.7'
cache: pip
install: pip install -r requirements.txt -t .
script: python test_load.py
deploy:
  provider: lambda
  function_name: xduroResultPoll
  region: eu-west-2
  role: arn:aws:iam::164526544718:role/s3_rw
  runtime: python2.7
  module_name: load
  handler_name: runPoll
  timeout: 60
  access_key_id:
    secure: PdysBvyVXuWkcJeBXxL0eZ/FR4ZMRBIL6FvplNjOHQ8tfjicN8W9XOKwUUTKW74pDNPxI54WzwLp9r7LbnLdb9aMzslz2TwKCLxKBF69bIgohqNLLmbO/wtst/4NEXq86RWTvmT+Rjrfp2tfBvcUnVcbCmnIjEWI55X1l91xPaQseKqzTp3KWcrELQAK/IxLzryh9fVcoLZRraBVSHy56k18UtcpPBXOlxX/MMkLa1QgfgzjxtpwUQFRfU4qA+H3aP46YG2Q9pAN7a8bssuThvsp9Tm59QA+ygtQuMlSuMr1y0P6KbL1U7fyjr/F1frtT0PDIBhxcIIqNhGBEiy1bd5mCMtYqzuSO1YFYnfBfANMb18l3SrREIH+dZbrDduC6MLCLhMT4/riVwl4JZ9k8f14dWKu50Ebicr/UZAgCTaCdXuLyUvHWk8pbFcCcBFegIZgCZr8LfS1AETRy8c81ekQ3G/dQwPL+teQF7CpGiHF5yypwaKPlOiRby/dhNQ4f/B9W/GOlY8/kY37+nhGyJfxZb0jCXWZhSD+t+7dFrcX0xIPnO27I9YA8u3cRW4kDqtOlQJHNmmKuEBBKPiVMA0pX1MYZG+0+8LvtEDOzWwOg61isORrGFQ5UBb0DXNU1kpM0TkKZAfsM33vIL5fwmUqvfy/hQ2rKjU7xZbSB5Y=
  secret_access_key:
    secure: SkPhfZcTqR7+M/bmxwywvNHn8K4M2Jj60FgBnGXJG/4IAD3sHKycScNqU7cu/QWtTVd8rPyAStaXKOO9cvWEu+wUrnytM98xlJISHR3NpurwRZJv/SJcSxQ11MGBUypHIatkX+/aylFKBa+VPHW/DQJhzWZJ/Y2yQ4wYFiAp6Oq9tjef2mivuXuGujXMZJX0x3vlWi++9B7Eby1Q03EhJfCedmwQOOlY1S7qV5sS8S8OaJQO6ZVbqZudkOYNEbtVxClSFSDVEAzdhTdefGX4+nZkgybXXrei2uGaM/vTWfQAGva2v2q9aKqMzrmIFwGztB7Hn4ke1WrzPulkClDiJDcO7HytNg/jvMZFg2/36J1WN8kDL5W862IJ/0hboK3sco+4bIRz2edBSsomBu4Ue1BeH2d1o+/d/4Ia21W9YeVJV1aadMOJR8vYNx8pu3e1oMuBCqCebtK+yrSKXvGHskcANdhDOx6S2JjcoUHZwQfwsb7OAfNS0POLN4VzmJKyA3fOYk6HoEyzNHd5SfokcBtHfN3w4sDeZ+6oBhA1WlGIpGYyIYSGN9RmbSERnGUHzbRVqev3ld1POaKDQk0lCjUYJVfw6wdiUhIsLHRxm6VgCuZYljT4foJ9Ug8YEeYk5OwVwS7nGxcNbHcrz4hap4b3llnp8oJRHS3VS9xPDVk=
