language: python
python: '2.7'
cache: pip
install: pip install -r requirements.txt -t .
script: python test_load.py
deploy:
  provider: lambda
  function_name: xduroResultPoll
  region: eu-west-2
  role: arn:aws:iam::164526544718:role/s3_rw
  runtime: python2.7
  module_name: load
  handler_name: runPoll
  access_key_id: AKIAJUHMSP5Z3ETDICZQ
  secret_access_key:
    secure: A/c6hHyVTYubqVfO1tjJxGl2d/fOp8/CTsjV1RNH5CYtI+6xJjBy7l+zbxu4jc0SHYy5IczbpPhDv1JFY+uiCdrv1Yhu0G9DF72rQaXRHtlvur1TZ6yKSRLD1EE4fm4JjyiDbj/I2tyTvHstN57Jh0UYIxB7B1VdyMhxRuvJMZF2bFBMT5Sbf+lb/2x+R6nvwsTo0XuSlFKGvI5spJxvyETqeietoS0fHsFQoBct5GOwMoKLY9GoASgBnV0zv/1DJwWt6fhLaA0qtyq6stkeGdT/Z+mr1zG9MBWHecyg+2NJ4MSCl6HYk7YnDJ49Ph13RcSwXvkscRfw6y8oldDPZqgcONmgB79ZLvl0lS7/r+nai6QdMJMSO7vuUGJE9QRWYcuw8b87aE74Ddis3bZyEvuvzkozHfnfnqaL84mos5wN/L/RC0CjTVHn364I9CggLbCbok6NKFsRDg0p92RuDN4RnTShgRvH085fGO6mS57PkVpRkEKxnmUBSsxCquIzgSQ9UW7gmrQwjIvC2Oa6/FOL8iYztGhU8SUGvqHmhgMr2GlKjHsEyvCYrHfYH2fJYYqWqICiWiHeMiiT6LHkjTINz87ItuVG1dfm5qc9Fni/WHyMsc6yk82VerVkOC/zatiByQzYAKunwWcTGRYHuBvlpWGuEwE79rt5zUHBr5U=
  timeout: 10